### PR TITLE
fix(backend): allow from_time and to_time to be the same

### PR DESCRIPTION
**Pull request by c0rydoras**
i noticed UX is worse when you can't have the same from and to time, also this would make it so 0:00 to 24:00 attendances aren't possible

### CODE REVIEW

**Review by winged — CHANGES_REQUESTED** [review]
Code change LGTM, but commit / PR will need some explanation. Why should this be allowed now?

**Comment by c0rydoras** [comment]
added them to the PR @winged

**Comment by winged** [comment]
Would it make sense to get rid of the ends-at-midnight special case and use 24:00 for that, also in the frontend?

**Comment by c0rydoras** [comment]
the frontend interprets a `to_time` of `0:00` as 24:00

**Comment by c0rydoras** [comment]
so this actually makes it work again

**Comment by winged** [comment]
> the frontend interprets a `to_time` of `0:00` as 24:00

Is this our code or some time library? Cause if it's our code, I'd prefer storing "ends at midnight" as 24:00 instead. Of course we'd need a migration for that, so maybe not worth it..

**Review by winged — APPROVED** [review]
Feel free to merge. 

Due to complexity of changing things to be "right", it may not be worth doing the migrations and code changes in the frontend etc.

**Comment by c0rydoras** [comment]
if this is a thing you want implemented feel free to open an issue :)

**Pull request merged**
