### PR TITLE
chore(frontend): drop commitlint

### PR DESCRIPTION
**Pull request by c0rydoras**

### CODE REVIEW

**Comment by derrabauke** [comment]
Why?

**Comment by c0rydoras** [comment]
because it isn't used anymore ^^

**Comment by derrabauke** [comment]
Obviously :man_facepalming: sorry. But is there an alterantive in place? `pre-commit`?

**Comment by c0rydoras** [comment]
not really, pre-commit was also dropped at some point iirc

**Comment by derrabauke** [comment]
> not really, pre-commit was also dropped at some point iirc

I would strongly suggest to set this up again. Saves a lot of headache when using sem-ver releases with auto changelog generation.

**Comment by c0rydoras** [comment]
yea but we don't need it in our frontends dependencies

**Comment by c0rydoras** [comment]
> I would strongly suggest to set this up again. Saves a lot of headache when using sem-ver releases with auto changelog generation.

why? our changelog doesn't look at that bad? https://github.com/adfinis/timed/releases

**Comment by derrabauke** [comment]
> > I would strongly suggest to set this up again. Saves a lot of headache when using sem-ver releases with auto changelog generation.
> 
> why? our changelog doesn't look at that bad? https://github.com/adfinis/timed/releases

I does cause you adhere to the commitlint conventions. But imagine a junior dev joining the team who doesn't know. ;)

**Review by derrabauke — APPROVED** [review]
Anyways, it's the right strategy to remove the dep here.

**Pull request merged**
